apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker-service
  name: kafka-broker-service
  namespace: kafka
spec:
  ports:
    - port: 9092
  selector:
    app: broker1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: broker1
  name: broker1
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker1
  template:
    metadata:
      labels:
        app: broker1
    spec:
      hostname: broker1
      containers:
        - env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: <ZOOKEEPER-INTERNAL-IP>:2181
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-broker:9092
        - image: confluentinc/cp-zookeeper:7.3.0
          imagePullPolicy: IfNotPresent
          name: broker1
          ports:
            - containerPort: 9092
