apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service
  name: zookeeper-service
  namespace: kafka
spec:
  type: NodePort
  ports:
    - name: zookeeper-port
      port: 2181
      nodePort: 30181
      targetPort: 2181
  selector:
    app: zookeeper1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper1
  name: zookeeper1
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper1
  template:
    metadata:
      labels:
        app: zookeeper1
    spec:
      containers:
        - image: confluentinc/cp-zookeeper:7.3.0
          imagePullPolicy: IfNotPresent
          name: zookeeper1
          ports:
            - containerPort: 2181
