apiVersion: v1
kind: Service
metadata:
  labels:
    app: graphite-service
  name: graphite-service
  namespace: graphite
spec:
  type: NodePort
  ports:
    - name: graphite-port
      port: 80;81;2003-2004;2023-2024;8125;8126
      nodePort: 80;81;2003-2004;2023-2024;8125;8126
      targetPort: 80;81;2003-2004;2023-2024;8125;8126
  selector:
    app: graphite
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: graphite
  name: graphite
  namespace: graphite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphite
  template:
    metadata:
      labels:
        app: graphite
    spec:
      containers:
        - image: graphiteapp/graphite-statsd
          imagePullPolicy: IfNotPresent
          name: graphite
          ports:
            - containerPort: 80
            - containerPort: 81
            - containerPort: 2003-2004
            - containerPort: 2023-2024
            - containerPort: 8125
            - containerPort: 8126
