apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-service
  name: grafana-service
  namespace: grafana
spec:
  type: NodePort
  ports:
    - name: grafana-port
      port: 3000
      nodePort: 3000
      targetPort: 3000
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - image: grafana/grafana
          imagePullPolicy: IfNotPresent
          name: grafana
          ports:
            - containerPort: 3000
