{
 "title": "PM : Patient Streaming Score",
 "tags": [ "patient_streaming_score" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device",
    "query": {}
   },
   {
    "name": "patient",
    "label": "Patient",
    "query": {}
   },
   {
    "name": "id",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "BREATHING - $patient",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "target": "BREATHING.*.$id" }
   ]
  },
  {
   "title": "CONSCIOUSNESS - $patient",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "target": "CONSCIOUSNESS.*.$id" }
   ]
  },
  {
   "title": "HEART - $patient",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasSub(HEART.*.$id, 'HEART.', '')"
    }
   ]
  },
  {
   "title": "OXYGEN SATURATION ONE - $patient",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "target": "OXYGEN-SATURATION-ONE.*.$id" }
   ]
  },
  {
   "title": "OXYGEN SATURATION TWO - $patient",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "target": "OXYGEN-SATURATION-TWO.*.$id" }
   ]
  },
  {
   "title": "RESPIRATORY - $patient",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "target": "RESPIRATORY.*.$id" }
   ]
  },
  {
   "title": "SYSTOLIC BLOOD PRESSURE - $patient",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "target": "SYSTOLIC-BLOOD-PRESSURE.*.$id" }
   ]
  },
  {
   "title": "TEMPERATURE - $patient",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "target": "TEMPERATURE.*.$id" }
   ]
  }
 ]
}